backend:
  name: test-repo

media_folder: static/assets
public_folder: assets

collections:
  - name: docs
    label: Documents
    folder: docs
    create: true
    fields:
      - {name: title, label: Title}
      - {name: body, label: Body, widget: markdown}
